const posts = {
  items: [
    {
      id: 1,
      state: "모집중",
      title: "[ToyProject] 백앤드 개발자 구해요!",
      who: "재신",
      detail: "mysql, nodejs 사용 가능하신 개발자 두 분 구합니다.",
      termStart: "2022-04-30",
      termEnd: "2022-05-05",
      count: 2,
      totalCount: 4,
    },
    {
      id: 2,
      state: "모집중",
      title: "[ToyProject] 프론트 개발자 구해요!",
      who: "지후",
      detail: "로그인, 회원가입, 글쓰기 등 구현하실 개발자 두 분 구합니다.",
      termStart: "2022-04-30",
      termEnd: "2022-05-05",
      count: 2,
      totalCount: 4,
    },
    {
      id: 3,
      state: "모집중",
      title: "[React] 개발자 구해요!",
      who: "용남",
      detail: "쇼핑몰 웹페이지 구현하실 개발자 두 분 구합니다.",
      termStart: "2022-04-30",
      termEnd: "2022-05-05",
      count: 3,
      totalCount: 4,
    },
    {
      id: 4,
      state: "모집완료",
      title: "[웹페이지제작] 개발자 구해요!",
      who: "시우",
      detail: "쇼핑몰 웹페이지 구현하실 프론트 개발자 두 분 구합니다.",
      termStart: "2022-04-30",
      termEnd: "2022-05-05",
      count: 3,
      totalCount: 4,
    },
  ],
};

export default posts;
